#pragma once
#include <string>
#include <vector>
#include <map>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <chrono>
#include <iomanip>

namespace qasm {

// =========================================================================
// WORKSPACE NOTATION SYSTEM
// The AI has a dedicated folder structure for its outputs.
// File paths are generated by the system, never hardcoded per-file.
// Notation:
//   output/txt/      -> prose, journals, notes (.txt)
//   output/docs/     -> structured documents (.md, .doc)
//   output/code/     -> programs, scripts (.py, .cpp, .js, .sh)
//   output/programs/ -> executables and compiled scripts
//   output/memory/   -> compressed .aht semantic memory slots
// =========================================================================

struct MemorySlot {
    std::string id;         // Unique Base-138 fingerprint
    std::string filepath;   // Physical path on disk
    std::string content;    // Raw content
    float entropy;          // Snapshot of internal_entropy at write time
    float dopamine;         // Snapshot of dopamine_level at write time
};

// Systema Musimatica-138
// A placeholder class representing a number encoded in Base-138.
class Base138 {
public:
    std::string encoded_value;

    Base138() : encoded_value("") {}
    Base138(const std::string& value) : encoded_value(value) {}

    // Convert from a standard uint64_t to Base138 representation
    static Base138 from_uint64(uint64_t value);

    // Convert string to Base138 encoded representation
    static Base138 encode_string(const std::string& input);

    // =========================================================
    // The Bala Tor Calculus (True High-Dimensional Vector Math)
    // =========================================================
    
    // Tainsin: Calculates the Cosine Similarity (Derivative distance) between two Tain vectors
    static float calculate_tainsin(const std::vector<float>& vecA, const std::vector<float>& vecB);
    
    // Kesh: Calculates the Geometric Centroid (Integral) of an array of Tain vectors
    static std::vector<float> calculate_kesh(const std::vector<std::vector<float>>& vectors);

    // =========================================================================
    // MUSICAL NOTATION COMPRESSION (Systema Musimatica-138)
    // Encodes raw data into a compact musical chord notation string.
    // Each 'chord' represents a compressed block of semantic data.
    // Format: [NOTE][OCTAVE][DUR] e.g. C4Q = C, octave 4, Quarter note
    // Notes:     C D E F G A B + sharps (#) = 14 note classes
    // Octaves:   0-9
    // Durations: W(hole) H(alf) Q(uarter) E(ighth) S(ixteenth)
    // Velocity:  p(iano/soft) m(ezzo) f(orte/loud) — encodes magnitude
    // A full measure holds 12 chord-atoms, yielding 14*10*5*3 = 2100 unique states per atom
    // =========================================================================

    // Compress arbitrary string/data into musical notation string
    static std::string encode_musical_notation(const std::string& data);

    // Decode a musical notation string back to original data
    static std::string decode_musical_notation(const std::string& notation);

    // Generate a unique, timestamped workspace file path
    // type: "txt" | "docs" | "code" | "programs" | "memory"
    // ext:  file extension without dot e.g. "txt", "py", "md"
    static std::string generate_workspace_path(const std::string& type, const std::string& ext, const std::string& hint = "");

    // Write a new file to the workspace (never overwrites — always unique path)
    static bool workspace_write(const std::string& type, const std::string& ext, const std::string& content, const std::string& hint, std::string& out_path);
};

} // namespace qasm
